# Generated by Django 5.2.7 on 2026-04-05 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('devices', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='biometriclog',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_logs', to='devices.device'),
        ),
        migrations.AddField(
            model_name='employeeshift',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='employeeshift',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_shifts', to='attendance.shift'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date'], name='idx_att_date'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['status'], name='idx_att_status'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='uniq_emp_att_date'),
        ),
        migrations.AddConstraint(
            model_name='biometriclog',
            constraint=models.UniqueConstraint(fields=('device', 'employee_code', 'timestamp', 'action'), name='uniq_bio_log_device_emp_ts_act'),
        ),
    ]
