# Generated by Django 5.2.11 on 2026-04-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='name_en',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
