# Generated by Django 5.2.7 on 2026-04-25 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_shift_description_en_shift_name_en'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['name']},
        ),
    ]
