# Generated by Django 5.2.7 on 2026-02-04 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_device_sync_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to='core.employee'),
        ),
        migrations.AddField(
            model_name='department',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
