# Generated by Django 5.2.7 on 2026-02-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_employee_address_employee_birth_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="permissions",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
