# Generated by Django 5.2.7 on 2026-02-04 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_employee_document"),
    ]

    operations = [
        migrations.CreateModel(
            name="BiometricLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("employee_code", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField()),
                ("action", models.CharField(choices=[("check_in", "Check In"), ("check_out", "Check Out")], max_length=20)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                ("device", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="biometric_logs", to="core.device")),
            ],
            options={"ordering": ["-timestamp"]},
        ),
    ]
