# Generated by Django 5.2.11 on 2026-04-06 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('attendance', 'Attendance & Time Tracking'), ('leaves', 'Leave & Absence'), ('compensation', 'Compensation & Benefits'), ('conduct', 'Code of Conduct'), ('general', 'General HR Policies')], default='general', max_length=50)),
                ('content', models.TextField(help_text='The actual text layout of the policy')),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Policy Document',
                'verbose_name_plural': 'Policy Documents',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='AIInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('response', models.TextField()),
                ('context_metadata', models.JSONField(default=dict, help_text='Metadata about analytical snapshots or policy versions used')),
                ('tokens_used', models.IntegerField(default=0)),
                ('response_time_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Interaction',
                'verbose_name_plural': 'AI Interactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
