# Generated by Django 5.2.11 on 2026-04-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='name_en',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='role',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_en',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
