# Generated by Codex on 2026-04-05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="biometrictemplate",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="biometrictemplate",
            name="conflict_strategy",
            field=models.CharField(default="last_write_wins", max_length=50),
        ),
        migrations.AddField(
            model_name="biometrictemplate",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="biometrictemplate",
            name="last_distributed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="biometrictemplatedistribution",
            name="requested_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="devicebackupsnapshot",
            name="scope",
            field=models.CharField(default="device", max_length=50),
        ),
        migrations.AddField(
            model_name="devicebackupsnapshot",
            name="device_group",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="devices.devicegroup"),
        ),
        migrations.AddField(
            model_name="devicebackupsnapshot",
            name="created_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="devicebackupsnapshot",
            name="restored_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="devicecommandapproval",
            name="rejected_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="dev_cmd_rej", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="devicefirmwarerollout",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="devicefirmwarerollout",
            name="rollout_plan",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="devicefirmwarerollout",
            name="results",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="devicefirmwarerollout",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="devicefirmwarerollout",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
