# Generated by Codex on 2026-04-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0002_expand_device_management_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="biometrictemplate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
