# Generated by Django 5.2.11 on 2026-04-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_add_biometric_template_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='location_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='device',
            name='name_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='devicegroup',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='devicegroup',
            name='name_en',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='devicepolicy',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='devicepolicy',
            name='name_en',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
