# Generated by Codex on 2026-04-08

from django.db import migrations, models


def forwards(apps, schema_editor):
    DeviceBackupSnapshot = apps.get_model("devices", "DeviceBackupSnapshot")
    DeviceBackupSnapshot.objects.filter(scope="device").update(scope="single")


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0004_device_location_en_device_name_en_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
        migrations.AddField(
            model_name="devicebackupsnapshot",
            name="name_en",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="devicebackupsnapshot",
            name="scope",
            field=models.CharField(
                choices=[("single", "Single"), ("group", "Group"), ("global", "Global")],
                default="single",
                max_length=50,
            ),
        ),
    ]
