# Generated by Codex on 2026-04-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0005_devicebackupsnapshot_bilingual_fields_and_scope_choice"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicecommandapproval",
            name="reason_en",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="devicefirmwarerollout",
            name="notes_en",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="devicesynclog",
            name="reason_en",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
