# Generated by Django 5.2.7 on 2026-04-25 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_device_free_text_bilingual_fields'),
        ('employees', '0006_alter_asset_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='employees.department'),
        ),
    ]
