# Generated by Django 5.2.11 on 2026-04-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_department_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='category_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='asset',
            name='name_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='recruitmentcandidate',
            name='position_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='recruitmentcandidate',
            name='source_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='provider_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='title_en',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
