# Generated by Codex on 2026-04-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_asset_category_en_asset_name_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeedocument",
            name="doc_type_en",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="employeedocument",
            name="title_en",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
