# Generated by Codex on 2026-04-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0004_employee_document_bilingual_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="notes_en",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="employeedocument",
            name="notes_en",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="leave",
            name="reason_en",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="performancereview",
            name="notes_en",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="recruitmentcandidate",
            name="notes_en",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="trainingrecord",
            name="notes_en",
            field=models.TextField(blank=True),
        ),
    ]
