# Generated by Django 5.2.7 on 2026-04-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticalMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('attendance_rate', 'Attendance Rate'), ('late_rate', 'Late Rate'), ('leave_requests', 'Leave Requests'), ('payroll_total', 'Payroll Total'), ('headcount', 'Headcount')], max_length=50)),
                ('scope', models.CharField(default='global', max_length=50)),
                ('scope_id', models.IntegerField(blank=True, null=True)),
                ('value', models.FloatField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['metric_type', 'period_start'], name='idx_metric_type_dt')],
            },
        ),
    ]
