# Generated by Django 5.2.11 on 2026-04-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_analytical_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricTrendFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100)),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('value', models.FloatField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-start_date', 'metric_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='dailydashboardsnapshot',
            options={'ordering': ['-date'], 'verbose_name': 'Daily Dashboard Snapshot'},
        ),
        migrations.AlterModelOptions(
            name='departmentdistributionsnapshot',
            options={'ordering': ['-date', '-employee_count'], 'verbose_name': 'Department Distribution Snapshot'},
        ),
        migrations.AddIndex(
            model_name='systemactivityfact',
            index=models.Index(fields=['activity_type', 'date'], name='idx_activity_type_dt'),
        ),
        migrations.AddIndex(
            model_name='metrictrendfact',
            index=models.Index(fields=['metric_name', 'period_type', 'start_date'], name='idx_trend_metric_lookup'),
        ),
    ]
