# Generated by Django 5.2.11 on 2026-04-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_metrictrendfact_alter_dailydashboardsnapshot_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentdistributionsnapshot',
            name='department_name_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='systemactivityfact',
            name='action_en',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
