import json, copy

# All missing keys with their Arabic translations
MISSING_TRANSLATIONS = {
    "filter_range": "نطاق الوقت",
    "day_sat": "سبت",
    "day_sun": "أحد",
    "day_mon": "إثن",
    "day_tue": "ثلاث",
    "day_wed": "أربع",
    "day_thu": "خمس",
    "day_fri": "جمع",
    "dept_admin": "الإدارة",
    "dept_sales": "المبيعات",
    "dept_tech": "التقنية",
    "dept_hr": "الموارد البشرية",
    "employees_list_count": "قائمة الموظفين ({{count}})",
    "search_employee_placeholder": "البحث عن موظف...",
    "employee_id_required": "الرقم الوظيفي مطلوب",
    "action": "الإجراء",
    "model": "الطراز",
    "object_id": "معرف الكائن",
    "delete_employee_title": "حذف موظف",
    "delete_employee_desc": "هل أنت متأكد من حذف الموظف \"{{name}}\"؟ لا يمكن التراجع عن هذا الإجراء.",
    "sync_time_failed": "فشل مزامنة وقت الجهاز",
    "reboot_failed": "فشل إعادة تشغيل الجهاز",
    "pull_logs_failed": "فشل سحب السجلات",
    "push_employee_failed": "فشل إرسال بيانات الموظف",
    "sync_success": "اكتملت المزامنة",
    "reboot": "إعادة التشغيل",
    "pull_logs": "سحب السجلات",
    "push_employee": "إرسال بيانات الموظف",
    "employee_code": "كود الموظف",
    "send": "إرسال",
    "sync_logs": "مزامنة السجلات",
    "sync_time": "مزامنة الوقت",
    "port": "المنفذ",
    "comm_key": "مفتاح الاتصال",
    "bulk_action": "إجراء جماعي",
    "run_bulk": "تشغيل على المحددة",
    "reason_optional": "السبب (اختياري)",
    "failed_commands": "فاشل",
    "total_commands": "الإجمالي",
    "uptime": "وقت التشغيل %",
    "failure_rate": "معدل الفشل",
    "failure_level_high": "عالي",
    "failure_level_medium": "متوسط",
    "failure_level_low": "منخفض",
    "devices_health_summary": "صحة الأجهزة (30 يوماً)",
    "inactive_devices": "غير نشط",
    "average_failure_rate": "متوسط معدل الفشل",
    "devices_needing_attention": "أجهزة تحتاج انتباهاً",
    "health_report_details": "تفاصيل تقرير الصحة (30 يوماً)",
    "generated_at": "صُدر في",
    "health_report_empty": "لا توجد بيانات لتقرير الصحة.",
    "health_hint_inactive": "غير نشط = لا يوجد نشاط أو إشارة حية خلال نافذة التقرير.",
    "bulk_hint_select_devices": "اختر جهازاً أو أكثر لعرض الإجراءات الجماعية.",
    "advanced_device_control": "التحكم المتقدم بالأجهزة",
    "advanced_controls_hint": "للأوامر الحساسة والسياسات والموافقات.",
    "open_command_center": "فتح مركز الأوامر",
    "devices_advanced_moved_hint": "الأوامر المتقدمة والموافقات والسياسات والنسخ الاحتياطية نُقلت إلى مركز الأوامر.",
    "command_center_selected_hint": "الأجهزة المحددة تم تحميلها من صفحة الأجهزة ويمكن استهدافها مباشرة.",
    "command_center_group_hint": "يمكنك استهداف مجموعة أجهزة مباشرة من مركز الأوامر.",
    "hide_advanced_controls": "إخفاء",
    "show_advanced_controls": "عرض",
    "limit_optional": "الحد (اختياري)",
    "attendance_summary": "ملخص الحضور",
    "leaves_summary": "ملخص الإجازات",
    "edit_department": "تعديل القسم",
    "job_titles_title": "المسميات الوظيفية",
    "job_titles_subtitle": "إدارة المسميات ونطاقات الرواتب",
    "add_job_title": "إضافة مسمى وظيفي",
    "job_titles_list": "قائمة المسميات الوظيفية",
    "job_title_ar": "المسمى الوظيفي (عربي)",
    "job_title_en": "المسمى الوظيفي (إنجليزي)",
    "level": "المستوى",
    "select_level": "اختر المستوى",
    "level_executive": "تنفيذي",
    "level_manager": "مدير",
    "level_specialist": "متخصص",
    "level_junior": "مبتدئ",
    "level_senior": "متقدم",
    "sort_department": "ترتيب بالقسم",
    "sort_level": "ترتيب بالمستوى",
    "salary_range": "نطاق الراتب",
    "min_salary": "الراتب الأدنى",
    "max_salary": "الراتب الأعلى",
    "job_description": "الوصف الوظيفي",
    "level_required": "المستوى مطلوب",
    "department_required": "القسم مطلوب",
    "min_salary_required": "الحد الأدنى للراتب مطلوب",
    "max_salary_required": "الحد الأعلى للراتب مطلوب",
    "salary_range_invalid": "نطاق الراتب غير صالح",
    "job_updated": "تم تحديث المسمى",
    "job_updated_desc": "تم حفظ المسمى الوظيفي بنجاح",
    "job_added": "تم إضافة المسمى",
    "job_added_desc": "تم إنشاء المسمى الوظيفي بنجاح",
    "job_deleted": "تم حذف المسمى",
    "job_deleted_desc": "تم حذف المسمى الوظيفي",
    "delete_job_title": "حذف مسمى وظيفي",
    "delete_job_title_desc": "هل أنت متأكد من حذف {{name}}؟ لا يمكن التراجع عن هذا.",
    "cannot_delete_job_title": "لا يمكن حذف المسمى الوظيفي",
    "job_delete_has_employees": "يوجد موظفون مرتبطون بهذا المسمى",
    "base_salary": "الراتب الأساسي",
    "status_draft": "مسودة",
    "status_approved": "معتمد",
    "position": "الوظيفة",
    "export_csv": "تصدير CSV",
    "export_excel": "تصدير Excel",
    "login_title": "تسجيل الدخول",
    "show": "عرض",
    "search_training": "البحث في التدريبات...",
    "search_assets": "البحث في الأصول...",
    "leave_details_title": "تفاصيل الإجازة",
    "approval_log": "سجل الموافقات",
    "add_user": "إضافة مستخدم",
    "system_admins": "مديرو النظام",
    "role_permissions_hint": "منح صلاحيات محددة أو الاستيراث من الدور",
    "permissions_select_all": "تحديد جميع الصلاحيات",
    "permissions_clear_all": "مسح جميع الصلاحيات",
    "use_role_permissions": "استخدام صلاحيات الدور",
    "force_password_change": "إلزام تغيير كلمة المرور",
    "force_password_change_desc": "يجب على المستخدم تغيير كلمة المرور عند الدخول التالي",
    "select_role": "اختر الدور",
    "audit_logs_subtitle": "تتبع الإجراءات في جميع أنحاء النظام",
    "search_logs": "البحث في السجلات",
    "export_settings": "تصدير الإعدادات",
    "import_settings": "استيراد الإعدادات",
    "reset_defaults": "إعادة الضبط الافتراضي",
    "tab_company": "الشركة",
    "tab_general": "عام",
    "tab_attendance": "الحضور",
    "tab_leaves": "الإجازات",
    "tab_notifications": "الإشعارات",
    "company_desc": "المعلومات الأساسية للشركة",
    "no_logo": "لا يوجد شعار",
    "upload_logo": "رفع شعار",
    "company_name_ar": "اسم الشركة (عربي)",
    "company_name_en": "اسم الشركة (إنجليزي)",
    "company_email": "بريد الشركة",
    "company_phone": "هاتف الشركة",
    "company_address": "عنوان الشركة",
    "notifications_title": "الإشعارات",
    "notifications_desc": "تهيئة كيفية ووقت استلام المستخدمين للتنبيهات",
    "notification_channels_title": "قنوات الإشعارات",
    "email_notifications_title": "إشعارات البريد الإلكتروني",
    "email_notifications_desc": "إرسال التنبيهات عبر البريد الإلكتروني",
    "sms_notifications_title": "إشعارات الرسائل النصية",
    "sms_notifications_desc": "إرسال التنبيهات عبر الرسائل النصية",
    "notification_types_title": "أنواع الإشعارات",
    "leave_request_notify_title": "طلبات الإجازة",
    "leave_request_notify_desc": "إشعار المسؤولين عند تقديم أو تحديث طلبات الإجازة",
    "attendance_alerts_desc": "إرسال تنبيهات للغياب أو التأخير أو البصمة المكررة",
    "weekly_reports_desc": "إرسال ملخص أسبوعي للموارد البشرية بالبريد",
    "digest_frequency": "تكرار الملخص",
    "frequency_instant": "فوري",
    "notifications_enabled": "الإشعارات مفعّلة",
    "quiet_hours_start": "بداية ساعات الهدوء",
    "quiet_hours_end": "نهاية ساعات الهدوء",
    "quiet_hours_enabled": "تفعيل ساعات الهدوء",
    "quiet_hours_desc": "إيقاف البريد/الرسائل خارج ساعات العمل",
    "digest_time": "وقت الملخص",
    "digest_weekday": "يوم الملخص الأسبوعي",
    "weekday_sun": "الأحد",
    "weekday_mon": "الاثنين",
    "weekday_tue": "الثلاثاء",
    "weekday_wed": "الأربعاء",
    "weekday_thu": "الخميس",
    "weekday_fri": "الجمعة",
    "weekday_sat": "السبت",
    "notification_templates": "قوالب الإشعارات",
    "tpl_leave_request_sms_no_var": "تم استلام طلب إجازة جديد.",
    "tpl_leave_request_body_no_var": "تم تقديم طلب إجازة جديد.",
    "tpl_leave_approved_sms_no_var": "تمت الموافقة على الإجازة.",
    "tpl_leave_approved_body_no_var": "تمت الموافقة على الإجازة.",
    "tpl_leave_rejected_sms_no_var": "تم رفض الإجازة.",
    "tpl_leave_rejected_body_no_var": "تم رفض الإجازة.",
    "tpl_attendance_alert_sms_no_var": "تنبيه حضور.",
    "tpl_attendance_alert_body_no_var": "تنبيه حضور.",
    "tpl_weekly_report_sms_no_var": "التقرير الأسبوعي جاهز.",
    "tpl_weekly_report_body_no_var": "الملخص الأسبوعي جاهز.",
    "leave_title": "إعدادات الإجازات",
    "approval_single": "مستوى واحد",
    "attendance_settings_title": "إعدادات الحضور",
    "password_policy": "سياسة كلمة المرور",
    "password_policy_recommend": "تحميل الإعدادات الموصى بها",
    "advanced_options": "خيارات متقدمة",
    "enable_geolocation_title": "تفعيل الموقع الجغرافي",
    "enable_geolocation_desc": "تطلب تسجيل الموقع عند الدخول/الخروج",
    "onboarding_step_company": "بيانات الشركة",
    "onboarding_progress_label": "20%",
    "onboarding_company_name_ar": "اسم الشركة (عربي)",
    "onboarding_country": "الدولة",
    "onboarding_currency": "العملة",
    "onboarding_company_email": "بريد الشركة الإلكتروني",
    "onboarding_company_phone": "هاتف الشركة",
    "onboarding_company_address": "عنوان الشركة",
    "run_full_wizard": "تشغيل معالج الإعداد الكامل",
    "restart_wizard": "إعادة تشغيل معالج الإعداد",
    "settings_saved": "تم حفظ الإعدادات",
    "settings_saved_desc": "تم حفظ إعدادات {{section}} بنجاح",
    "company_name_placeholder": "مثال: شركة التقنية المتقدمة",
    "platform": "المنصة",
    "register": "تسجيل",
    "sort_position": "ترتيب بالوظيفة",
    "invalid_email": "بريد إلكتروني غير صالح",
    "invalid_phone": "رقم هاتف غير صالح",
    "work_time_invalid": "وقت العمل غير صالح",
    "import_failed": "فشل الاستيراد",
    # password_reset sub-keys missing
    "password_reset.code_title": "أدخل رمز التحقق",
    "password_reset.code_subtitle": "أرسلنا رمزاً مكوناً من 6 أرقام إلى {{email}}. أدخله مع كلمة المرور الجديدة.",
    "password_reset.code_label": "رمز التحقق",
    "password_reset.new_password": "كلمة المرور الجديدة",
    "password_reset.confirm_password": "تأكيد كلمة المرور",
    "password_reset.submit": "تأكيد وإعادة التعيين",
    "password_reset.success_desc": "تم إعادة تعيين كلمة المرور. يمكنك الآن تسجيل الدخول.",
    "password_reset.error_title": "حدث خطأ ما",
}

# Nested missing keys under "password_reset" (not dot-notation, real nesting)
MISSING_NESTED = {
    "password_reset": {
        "code_title": "أدخل رمز التحقق",
        "code_subtitle": "أرسلنا رمزاً مكوناً من 6 أرقام إلى {{email}}. أدخله مع كلمة المرور الجديدة.",
        "code_label": "رمز التحقق",
        "new_password": "كلمة المرور الجديدة",
        "confirm_password": "تأكيد كلمة المرور",
        "submit": "تأكيد وإعادة التعيين",
        "success_desc": "تم إعادة تعيين كلمة المرور. يمكنك الآن تسجيل الدخول.",
        "error_title": "حدث خطأ ما",
    }
}

# Flat missing keys (not nested)
MISSING_FLAT = {k: v for k, v in MISSING_TRANSLATIONS.items() if '.' not in k}

# Load existing ar.json
with open('d:/hr-companion-main/frontend/src/i18n/locales/ar.json', 'r', encoding='utf-8') as f:
    ar = json.load(f)

# Add flat missing keys
added_flat = 0
for k, v in MISSING_FLAT.items():
    if k not in ar:
        ar[k] = v
        added_flat += 1

# Add nested missing keys
added_nested = 0
for section, keys in MISSING_NESTED.items():
    if section in ar and isinstance(ar[section], dict):
        for k, v in keys.items():
            if k not in ar[section]:
                ar[section][k] = v
                added_nested += 1

print(f"Added {added_flat} flat keys")
print(f"Added {added_nested} nested keys")
print(f"Total keys now: {len(ar)}")

# Save
with open('d:/hr-companion-main/frontend/src/i18n/locales/ar.json', 'w', encoding='utf-8') as f:
    json.dump(ar, f, ensure_ascii=False, indent=2)

print("Done! ar.json saved.")
