import json

MISSING_BATCH_2 = {
    "employee_deleted": "تم حذف الموظف",
    "employee_deleted_desc": "تم حذف الموظف \"{{name}}\" بنجاح",
    "employee_updated": "تم تحديث الموظف",
    "employee_updated_desc": "تم تحديث بيانات الموظف بنجاح",
    "employee_added": "تم إضافة الموظف",
    "employee_added_desc": "تم إضافة الموظف بنجاح",
    "religion": "الديانة",
    "marital_status": "الحالة الاجتماعية",
    "single": "أعزب",
    "married": "متزوج",
    "divorced": "مطلق",
    "widowed": "أرمل",
    "basic_salary": "الراتب الأساسي",
    "allowances": "البدلات",
    "deductions": "الخصومات",
    "bank_name": "اسم البنك",
    "iban": "رقم الآيبان",
    "account_number": "رقم الحساب",
    "contract_start": "بداية العقد",
    "contract_end": "نهاية العقد",
    "probation_period": "فترة التجربة",
    "probation_end": "نهاية فترة التجربة",
    "emergency_contact": "جهة اتصال الطوارئ",
    "emergency_phone": "هاتف الطوارئ",
    "relation": "صلة القرابة",
    "step": "خطوة",
    "all": "الكل",
    "none": "لا شيء",
    "selected": "محدد",
    "items": "عنصر",
    "page": "صفحة",
    "rows_per_page": "صفوف في الصفحة",
    "sort_by": "ترتيب حسب",
    "ascending": "تصاعدي",
    "descending": "تنازلي",
    "apply": "تطبيق",
    "reset": "إعادة ضبط",
    "low": "منخفض",
    "medium": "متوسط",
    "high": "عالي",
    "urgent": "عاجل",
    "on_hold": "معلق مؤقتاً",
    "published": "منشور",
    "archived": "مؤرشف",
    "private": "خاص",
    "public": "عام",
    "internal": "داخلي",
    "external": "خارجي",
    "last_year": "السنة الماضية",
    "next_year": "السنة القادمة",
    "january": "يناير",
    "february": "فبراير",
    "march": "مارس",
    "april": "أبريل",
    "may": "مايو",
    "june": "يونيو",
    "july": "يوليو",
    "august": "أغسطس",
    "september": "سبتمبر",
    "october": "أكتوبر",
    "november": "نوفمبر",
    "december": "ديسمبر",
    "saturday": "السبت",
    "sunday": "الأحد",
    "monday": "الاثنين",
    "tuesday": "الثلاثاء",
    "wednesday": "الأربعاء",
    "thursday": "الخميس",
    "friday": "الجمعة",
    "old_password": "كلمة المرور القديمة",
    "new_password": "كلمة المرور الجديدة",
    "confirm_password": "تأكيد كلمة المرور",
    "email_notifications": "إشعارات البريد الإلكتروني",
    "sms_notifications": "إشعارات الرسائل النصية",
    "push_notifications": "الإشعارات الفورية",
    "language_settings": "إعدادات اللغة",
    "theme_settings": "إعدادات المظهر",
    "powered_by": "مدعوم بواسطة",
    "tpl_leave_request_sms": "طلب إجازة للموظف {{employee}}.",
    "tpl_leave_approved_subject": "تمت الموافقة على الإجازة",
    "tpl_leave_approved_body": "تمت الموافقة على إجازة {{employee}}.",
    "tpl_leave_approved_sms": "تمت الموافقة على إجازة {{employee}}.",
    "tpl_leave_rejected_subject": "تم رفض الإجازة",
    "tpl_leave_rejected_body": "تم رفض إجازة {{employee}}.",
    "tpl_leave_rejected_sms": "تم رفض إجازة {{employee}}.",
    "tpl_attendance_alert_sms": "تنبيه حضور للموظف {{employee}}.",
    "tpl_weekly_report_subject": "التقرير الأسبوعي للموارد البشرية",
    "tpl_weekly_report_body": "الملخص الأسبوعي جاهز.",
    "tpl_weekly_report_sms": "التقرير الأسبوعي جاهز.",
    "performance_title": "الأداء",
    "performance_subtitle": "مراجعات أداء الموظفين",
    "training_status_planned": "مخطط له",
    "training_status_in_progress": "قيد التنفيذ",
    "training_status_completed": "مكتمل",
    "training_status_cancelled": "ملغى",
    "assigned_to": "مخصص لـ",
    "company_name_en_example": "شركة التقنية المثالية",
    "sort_category": "ترتيب بالفئة",
    "import": "استيراد",
    "employee_form_add_title": "إضافة موظف",
    "employee_form_edit_title": "تعديل موظف",
    "employment_id": "الرقم الوظيفي",
    "select_department": "اختر القسم",
    "select_job_title": "اختر المسمى الوظيفي",
    "contract_status": "حالة العقد",
    "contract_permanent": "دائم",
    "contract_contract": "عقد",
    "contract_probation": "تجربة",
    "contract_terminated": "منتهي",
    "additional_details": "تفاصيل إضافية",
    "salary": "الراتب",
    "avatar_placeholder": "لم يتم اختيار ملف",
    "status_active": "نشط",
    "status_inactive": "غير نشط",
    "status_leave": "في إجازة",
    "date_placeholder": "يوم/شهر/سنة",
    "add_attendance": "إضافة حضور",
    "late_count": "متأخر",
    "sort_recent": "الأحدث",
    "close_day": "إغلاق اليوم",
    "import_logs": "استيراد السجلات",
    "sync_devices": "مزامنة الأجهزة",
    "attendance_record": "سجل حضور",
    "check_in_time": "وقت الدخول",
    "check_out_time": "وقت الخروج",
    "work_hours": "ساعات العمل",
    "status_present": "حاضر",
    "status_absent": "غائب",
    "status_late": "متأخر",
    "imported_attendance_records": "سجلات حضور مستوردة",
    "attendance_form_add_title": "إضافة سجل حضور",
    "shift_description": "وصف الوردية",
    "leave_form_add_title": "إضافة طلب إجازة",
    "select_leave_type": "اختر نوع الإجازة",
    "leave_reason_placeholder": "سبب الإجازة",
    "attachments": "المرفقات",
    "attachments_placeholder": "لم يتم اختيار ملف",
    "structure_title": "الهيكل التنظيمي",
    "structure_subtitle": "إدارة الأقسام والتسلسل الإداري",
    "add_department": "إضافة قسم",
    "department_tree": "شجرة الأقسام",
    "manager_label": "المدير",
    "department_name": "اسم القسم",
    "department_manager": "مدير القسم",
    "parent_department": "القسم الرئيسي",
    "parent_none": "بدون",
    "search_departments_placeholder": "بحث...",
    "command_palette_placeholder": "البحث عن الصفحات والإجراءات...",
    "command_palette_shortcut": "Ctrl+K",
    "toggle_sidebar": "تبديل الشريط الجانبي",
    "devices_offline_count": "{{count}} جهاز غير متصل",
    "devices_all_online": "جميع الأجهزة متصلة",
    "devices_refreshing": "جاري تحديث الحالة...",
    "devices_last_sync_hint": "يتم تحديث الحالة كل بضع ثوانٍ",
    "devices_last_sync": "آخر مزامنة",
    "devices_online": "متصل",
    "devices_offline": "غير متصل",
    "devices_view_mode": "وضع عرض الصفحة",
    "devices_mode_simple_hint": "عرض مبسط للاستخدام اليومي.",
    "devices_mode_advanced_hint": "عرض متقدم مع أدوات التحكم والموافقات والسياسات.",
    "view_mode_simple": "الوضع البسيط",
    "view_mode_advanced": "الوضع المتقدم",
    "last_heartbeat": "آخر نبض",
    "employee_count": "الموظفون",
    "sync_failed": "فشلت المزامنة",
}

with open('d:/hr-companion-main/frontend/src/i18n/locales/ar.json', 'r', encoding='utf-8') as f:
    ar = json.load(f)

added = 0
for k, v in MISSING_BATCH_2.items():
    if k not in ar:
        ar[k] = v
        added += 1

print(f"Added {added} keys")
print(f"Total keys now: {len(ar)}")

with open('d:/hr-companion-main/frontend/src/i18n/locales/ar.json', 'w', encoding='utf-8') as f:
    json.dump(ar, f, ensure_ascii=False, indent=2)

print("Done!")
